services:
  user-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: user_service
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  post-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: post_user
      POSTGRES_PASSWORD: post_password
      POSTGRES_DB: post_service
    ports:
      - "5434:5432"
    volumes:
      - post_data:/var/lib/postgresql/data

  keycloak-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  notification-cache:
    image: redis:latest
    ports:
      - "6380:6379" # Separate Redis instance for notification storage (if desired)

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  keycloak:
    image: keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin # Admin username
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin_password # Admin password
      KC_HOSTNAME_STRICT: false # Allows HTTP in development mode
      KC_HTTP_ENABLED: true # Explicitly enable HTTP
      KC_LOG_LEVEL: INFO
      KC_LOG_CONSOLE_OUTPUT: default
    command: start --import-realm  --http-enabled=true
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    volumes:
      - ./keycloak-realm-config/:/opt/keycloak/data/import/ # Import realm files

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api-gateway:
    build: ./api-gateway
    entrypoint:
      [
        "/app/wait-for-it.sh",
        "--timeout=60",
        "keycloak:8080",
        "--",
        "npm",
        "start",
      ]
    ports:
      - "80:3000"
    environment:
      - SESSION_SECRET=session_secret
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=social-media-platform
      - KEYCLOAK_CLIENT_ID=web-client
      - USER_SERVICE_URL=http://user-service:3000
    volumes:
      - ./scripts/wait-for-it.sh:/app/wait-for-it.sh # Mount wait-for-it.sh
    depends_on:
      - keycloak
      - user-service
      - post-service

  user-service:
    build: ./user-service
    entrypoint: ["/app/wait-for-it.sh", "user-db:5432", "--", "npm", "start"]
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgres://user_user:user_password@user-db/user_service
      - SESSION_SECRET=session_secret
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=social-media-platform
      - KEYCLOAK_CLIENT_ID=user-management-service
      - KEYCLOAK_CLIENT_SECRET=YXbgBO3JcrBOqfpzoMfQf2gPnfZrBTuw
      - KEYCLOAK_WEB_CLIENT_ID=web-client
    volumes:
      - ./scripts/wait-for-it.sh:/app/wait-for-it.sh # Mount wait-for-it.sh
    depends_on:
      - user-db

  post-service:
    build: ./post-service
    entrypoint: ["/app/wait-for-it.sh", "user-db:5432", "--", "npm", "start"]
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgres://post_user:post_password@post-db/post_service
      - SESSION_SECRET=session_secret
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=social-media-platform
      - KEYCLOAK_CLIENT_ID=post-management-service
      - KEYCLOAK_CLIENT_SECRET=wE1FPnBaMbd2GkcyyqQFO3s8Y7gfepk3
      - USER_SERVICE_URL=http://user-service:3000
    volumes:
      - ./scripts/wait-for-it.sh:/app/wait-for-it.sh # Mount wait-for-it.sh
    depends_on:
      - post-db

  notification-service:
    build: ./notification-service
    ports:
      - "3003:3000"
    environment:
      REDIS_HOST: notification-cache
    depends_on:
      - notification-cache
      - rabbitmq

  recommendation-service:
    build: ./recommendation-service
    ports:
      - "3004:3000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
      - rabbitmq

volumes:
  user_data:
  post_data:
  keycloak_data:
