import localFont from "next/font/local";
import Navbar from "@/components/fragments/navigation";
import { getAccessToken } from "@/lib/session";
import "./globals.css";
import { parseToken } from "@/lib/token";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const token = await getAccessToken();

  let userName = "";
  if (token) {
    const parsed = parseToken(token);
    userName = parsed.preferred_username;
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <Navbar isAuthenticated={!!token} userName={userName} />
        </header>
        {children}
      </body>
    </html>
  );
}
