import Navbar from "@/components/navigation";
import "./globals.css";
import { AuthProvider } from "@/components/auth-provider";
import { cookies } from "next/headers";
import { parseToken } from "@/lib/token";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const token = (await cookies()).get("access_token")?.value;

  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AuthProvider user={parseToken(token)}>
          <header>
            <Navbar />
          </header>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
