import Navbar from "@/components/navigation";
import "./globals.css";
import { AuthProvider } from "@/components/auth-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AuthProvider>
          <header>
            <Navbar />
          </header>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
